server:
  port: "8080"
  base_url: "http://localhost:8080"

database:
  user: "postgres"
  password: "password"
  name: "url_shortener"
  host: "localhost"
  port: "5432"
  sslmode: "disable"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  ttl_hours: 6